project:
  type: default
  title: "HetStaggeredDID_lab"
format:
  html:
    page-layout: full
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 300px
      gutter-width: 1.5rem
execute:
  freeze: true




